"""DOCX export — cached on NFS next to the media file (like srt/vtt)."""
from pathlib import Path


def _fmt(ms: int) -> str:
    h, rem = divmod(int(ms), 3600000)
    m, rem = divmod(rem, 60000)
    s = rem // 1000
    return f"{h:02d}:{m:02d}:{s:02d}"


def export_docx(video, transcript, segments, dest: Path):
    """Build {stem}.docx; segments = [{start_ms, text}]. Returns dest path."""
    from docx import Document

    doc = Document()
    doc.add_heading(video["filename"], level=1)
    doc.add_paragraph(f"Transcript — generated by Scriber ({transcript['model']})")

    doc.add_heading("Full text", level=2)
    doc.add_paragraph(transcript["full_text"] or "")

    doc.add_heading("Segments", level=2)
    table = doc.add_table(rows=1, cols=3)
    table.style = "Light Grid Accent 1"
    hdr = table.rows[0].cells
    hdr[0].text = "Time"
    hdr[1].text = "Speaker"
    hdr[2].text = "Text"
    for s in segments:
        row = table.add_row().cells
        row[0].text = _fmt(s["start_ms"])
        row[1].text = s.get("speaker") or ""
        row[2].text = s["text"]
    # W10: speaker column already wired for diarization output

    tmp = dest.with_suffix(".docx.tmp")
    doc.save(str(tmp))
    # cross-device safe (tmp on NFS via dest dir): rename is fine here since same dir
    tmp.replace(dest)
    return dest
